### ISSUE TITLE
flatten doesn't work

### ISSUE THREAD

**Issue by mdi** [gruntjs/grunt-contrib-copy#67]
With this task defined:

```
copy:
  build:
    files:
      expand: true
      flatten: true
      src: ['src/img/*', 'src/fonts/*']
      dest: 'public/assets/'
      filter: 'isFile'
```

I get the following error.

```
Warning: Object true has no method 'indexOf' Use --force to continue.
```

Stack trace:

```
    TypeError: Object true has no method 'indexOf'
    at /Users/mdi/src/lj-web/node_modules/grunt/lib/grunt/file.js:55:29
    at Array.forEach (native)
    at processPatterns (/Users/mdi/src/lj-web/node_modules/grunt/lib/grunt/file.js:53:34)
    at Object.file.expand (/Users/mdi/src/lj-web/node_modules/grunt/lib/grunt/file.js:110:17)
    at Object.fn [as src] (/Users/mdi/src/lj-web/node_modules/grunt/lib/grunt/task.js:176:36)
    at /Users/mdi/src/lj-web/node_modules/grunt-contrib-copy/tasks/copy.js:40:15
    at Array.forEach (native)
    at Object.<anonymous> (/Users/mdi/src/lj-web/node_modules/grunt-contrib-copy/tasks/copy.js:37:16)
    at Object.<anonymous> (/Users/mdi/src/lj-web/node_modules/grunt/lib/grunt/task.js:258:15)
    at Object.thisTask.fn (/Users/mdi/src/lj-web/node_modules/grunt/lib/grunt/task.js:78:16)
```
